/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as NotesSplatRouteImport } from './routes/notes.$'
import { Route as PProjectRouteImport } from './routes/p.$project'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as TTagRouteImport } from './routes/t.$tag'
import { Route as PProjectIndexRouteImport } from './routes/p.$project.index'
import { Route as PProjectCategoryRouteImport } from './routes/p.$project.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRoute,
} as any)
const NotesSplatRoute = NotesSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => NotesRoute,
} as any)
const PProjectRoute = PProjectRouteImport.update({
  id: '/p/$project',
  path: '/p/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TTagRoute = TTagRouteImport.update({
  id: '/t/$tag',
  path: '/t/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIndexRoute = PProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectCategoryRoute = PProjectCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => PProjectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/notes/$': typeof NotesSplatRoute
  '/p/$project': typeof PProjectRouteWithChildren
  '/s/$id': typeof SIdRoute
  '/t/$tag': typeof TTagRoute
  '/notes/': typeof NotesIndexRoute
  '/p/$project/$category': typeof PProjectCategoryRoute
  '/p/$project/': typeof PProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes/$': typeof NotesSplatRoute
  '/s/$id': typeof SIdRoute
  '/t/$tag': typeof TTagRoute
  '/notes': typeof NotesIndexRoute
  '/p/$project/$category': typeof PProjectCategoryRoute
  '/p/$project': typeof PProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteWithChildren
  '/notes/$': typeof NotesSplatRoute
  '/p/$project': typeof PProjectRouteWithChildren
  '/s/$id': typeof SIdRoute
  '/t/$tag': typeof TTagRoute
  '/notes/': typeof NotesIndexRoute
  '/p/$project/$category': typeof PProjectCategoryRoute
  '/p/$project/': typeof PProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notes'
    | '/notes/$'
    | '/p/$project'
    | '/s/$id'
    | '/t/$tag'
    | '/notes/'
    | '/p/$project/$category'
    | '/p/$project/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notes/$'
    | '/s/$id'
    | '/t/$tag'
    | '/notes'
    | '/p/$project/$category'
    | '/p/$project'
  id:
    | '__root__'
    | '/'
    | '/notes'
    | '/notes/$'
    | '/p/$project'
    | '/s/$id'
    | '/t/$tag'
    | '/notes/'
    | '/p/$project/$category'
    | '/p/$project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesRoute: typeof NotesRouteWithChildren
  PProjectRoute: typeof PProjectRouteWithChildren
  SIdRoute: typeof SIdRoute
  TTagRoute: typeof TTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof NotesRoute
    }
    '/notes/$': {
      id: '/notes/$'
      path: '/$'
      fullPath: '/notes/$'
      preLoaderRoute: typeof NotesSplatRouteImport
      parentRoute: typeof NotesRoute
    }
    '/p/$project': {
      id: '/p/$project'
      path: '/p/$project'
      fullPath: '/p/$project'
      preLoaderRoute: typeof PProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tag': {
      id: '/t/$tag'
      path: '/t/$tag'
      fullPath: '/t/$tag'
      preLoaderRoute: typeof TTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project/': {
      id: '/p/$project/'
      path: '/'
      fullPath: '/p/$project/'
      preLoaderRoute: typeof PProjectIndexRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/$category': {
      id: '/p/$project/$category'
      path: '/$category'
      fullPath: '/p/$project/$category'
      preLoaderRoute: typeof PProjectCategoryRouteImport
      parentRoute: typeof PProjectRoute
    }
  }
}

interface NotesRouteChildren {
  NotesSplatRoute: typeof NotesSplatRoute
  NotesIndexRoute: typeof NotesIndexRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesSplatRoute: NotesSplatRoute,
  NotesIndexRoute: NotesIndexRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface PProjectRouteChildren {
  PProjectCategoryRoute: typeof PProjectCategoryRoute
  PProjectIndexRoute: typeof PProjectIndexRoute
}

const PProjectRouteChildren: PProjectRouteChildren = {
  PProjectCategoryRoute: PProjectCategoryRoute,
  PProjectIndexRoute: PProjectIndexRoute,
}

const PProjectRouteWithChildren = PProjectRoute._addFileChildren(
  PProjectRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesRoute: NotesRouteWithChildren,
  PProjectRoute: PProjectRouteWithChildren,
  SIdRoute: SIdRoute,
  TTagRoute: TTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
